Application:
  simulation: true
Camera:
  port: 0
  frame_size: 640
  pattern_width_cm: 8
  distance: 30
  patter_width_pix: 155
  detectory_type: "aruco"
RobotControl:
  Robot:
    wheel_radius: 0.04
    radius: 0.1
    max_forward_speed: 2.5
    max_angular_speed: 2.5
    acceleration: 0.1
    dist_kp: 5.0
    dist_ki: 0.0
    dist_kd: 1.0
    dist_eps: 0.1
    angle_kp: 3.0
    angle_ki: 0.0
    angle_kd: 1.0
    angle_eps: 0.035
    set_point_x: 1.0
    set_point_y: 0.0
  VFH:
    Map:
      map_size: 81
      resolution: 5
      safety: 0.0
      cell_robot_radius: 2
      target_radius: 2
    Histogram:
      histogram_size: 40
      alpha: 2
      threshold_low: 250.0
      threshold_high: 350.0
      scaner_angle: 220.0
      density_b:
    max_narrow_size: 16
    mu_1: 5
    mu_2: 2
    mu_3: 2
